{
  "contest": 19,
  "handle": "cmichel",
  "address": "0x6823636c2462cfdcD8d33fE53fBCD0EdbE2752ad",
  "risk": "3",
  "title": "Funds are sent twice on `callTo` errors",
  "issueId": 9,
  "issueUrl": "https://github.com/code-423n4/2021-07-connext-findings/issues/9"
}